FROM golang:alpine as ali

WORKDIR /app

COPY main.go ./
 
RUN go env -w GO111MODULE=auto 

RUN go build main.go

FROM alpine

LABEL name="Golang Application" \    
      maintainer="Ali Kahoot <kahoot.ali@outlook.com>" \
      summary="A Golang Sample application"  
EXPOSE 8080 
COPY --from=ali /app/main ./main

CMD ["./main"]