FROM ubuntu
# Hello, How are you? Students of Batch # 7


# ENTRYPOINT ["/bin/echo"]
# CMD ["Hello, How are you? Students of Batch # 7"]

# ENTRYPOINT ["/bin/echo", "Hello, How are you? Students of Batch # 7"]
# CMD ["We are fine"]

# ENTRYPOINT [""]
# CMD ["/bin/echo", "Hello, How are you? Students of Batch # 7"]

# ENTRYPOINT ["/bin/echo", "Hello, How are you? Students of Batch #"]
# CMD ["7"]