FROM ubuntu
# Hello, How are you? Students of Batch # 6


# ENTRYPOINT ["/bin/echo"]
# CMD ["Hello, How are you? Students of Batch # 6"]

# ENTRYPOINT ["/bin/echo", "Hello, How are you? Students of Batch # 6"]
# CMD [""]

# ENTRYPOINT [""]
# CMD ["/bin/echo", "Hello, How are you? Students of Batch # 6"]

# ENTRYPOINT ["/bin/echo", "Hello, How are you? Students of Batch #"]
# CMD ["6"]