FROM ubuntu
# Our container should print 
# Hello, How are you? Students of Section A or B

# 1st option
# ENTRYPOINT ["/bin/echo"]
# CMD ["Hello, How are you? Students of Section A or B"]

# 2nd option
# ENTRYPOINT ["/bin/echo", "Hello, How are you? Students of Section A or B"]
# CMD [""]

# 3rd Option
# ENTRYPOINT [""]
# CMD ["/bin/echo", "Hello, How are you? Students of Section A or B"]

# 4th options
# ENTRYPOINT ["/bin/echo", "Hello, How are you? Students of Section"]
# CMD ["A or B"]